# Generated by Django 4.2.21 on 2025-05-23 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('handicap', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('hole_number', models.IntegerField(help_text='Which hole is the launch monitor setup on')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ball_speed', models.FloatField(blank=True, help_text='mph', null=True)),
                ('club_head_speed', models.FloatField(blank=True, help_text='mph', null=True)),
                ('launch_angle', models.FloatField(blank=True, help_text='degrees', null=True)),
                ('spin_rate', models.FloatField(blank=True, help_text='rpm (backspin)', null=True)),
                ('side_spin_rate', models.FloatField(blank=True, help_text='rpm', null=True)),
                ('carry_distance', models.FloatField(blank=True, help_text='yards', null=True)),
                ('total_distance', models.FloatField(blank=True, help_text='yards', null=True)),
                ('smash_factor', models.FloatField(blank=True, null=True)),
                ('apex_height', models.FloatField(blank=True, help_text='feet', null=True)),
                ('lateral_deviation', models.FloatField(blank=True, help_text='yards', null=True)),
                ('attack_angle', models.FloatField(blank=True, help_text='degrees', null=True)),
                ('club_path', models.FloatField(blank=True, help_text='degrees', null=True)),
                ('face_angle', models.FloatField(blank=True, help_text='degrees', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='golf_metrics_app.golfer')),
            ],
            options={
                'verbose_name_plural': 'Shot Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Group 1' or 'Smith Foursome'", max_length=100)),
                ('tee_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='golf_metrics_app.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.AddField(
            model_name='golfer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golfers', to='golf_metrics_app.group'),
        ),
    ]
